- acceptance/bake_test.go
- builder/zipper.go
- builder/zipper_test.go
When zipping files, their modified time header is set to now rather than
defaulting to 29 November 1979.
This was causing the ruby zip library used by OM to produce a pesky warning: "Invalid date/time in zip entry"
Signed-off-by: Panagiotis Xynos <panagiotis.xynos@engineerbetter.com>
> Set zip modified time to Now

- builder/zipper.go
Since releases are already compressed, a lot of time is spent
compressing/decompressing that does not significantly change the
file size.
> Do not compress the contents of the tile

- commands/fetch_test.go
- fetcher/compiled_releases_regexp_test.go
- fetcher/release_matcher.go
- fetcher/release_matcher_test.go
- internal/cargo/manifest.go
In lieu of using a configurable regex in `assets.yml`, this PR hard-codes the regex.
The new hard-coded regex is `^.+/(?P<release_name>[a-z-_0-9]+)-(?P<release_version>v?[0-9\.]+(-\w+)??)-(?P<stemcell_os>([a-z_]*-?){1,2})-(?P<stemcell_version>\d+\.\d+)(\.0)?\.tgz$`. In particular, this matches `-lts` release versions, and is agnostic as to S3 directory structure.
There are future improvements that can be made to configurability, some of which might involve removing the regex now that it's an internal implementation detail.
We're making this change because seriously, look at that regex, it's awful, are we really asking users to configure and understand it? 🙀
> Remove regex from assets.yml

- builder/interpolator.go
- builder/interpolator_test.go
Prior to this change, tiles created with --stub-releases would often
fail to upload properly to Ops Manager.
This is problematic since the --stub-releases
feature exists primarily to aid tile developers in iterating more
quickly on UI changes with a real Ops Manager.
https://github.com/pivotal-cf/kiln/issues/43
https://www.pivotaltracker.com/story/show/172467082
> Create stub metadata when no tgz file exists

- README.md
- acceptance/help_test.go
- commands/pre_process.go
- internal/cargo/kilnfile.go
- internal/preprocess/init_test.go
- internal/preprocess/preprocess.go
- internal/preprocess/preprocess_test.go
- internal/preprocess/test_data/malformed-expression/base.yml
- internal/preprocess/test_data/missing-key/base.yml
- internal/preprocess/test_data/nothing-to-pre-process/base.yml
- internal/preprocess/test_data/valid/base.yml
- internal/preprocess/test_data/valid/instance_groups/some_instance_group.yml
- internal/preprocess/walk.go
- main.go
We do this with a large internal tile. Having this work is the first step in improving kiln's ability to lint our tile repos more effectively.
I would appreciate feedback on the user experience and code review :)
To try this out locally
- clone kiln
- run ./install.sh
- cd to some large tile that has templating (ahem p-runtime)
- run something like `kiln pre-process --name ert --tile-names=ert,srt` or `kiln pre-process -n ert -tn=ert,srt`
- see the tile's files after executing the templates, the instance_groups directory is probably the most interesting
> kiln can pre-process tile repos

- go.mod
- go.sum
Supersedes: #253, #252, #251, #250, #249, #248, #245, ... #226
This is a "minor" bump. The tests passed locally.
Given CI integration tests are not green, I don't
expect this bump to fix that.
Authored-by: Christopher Hunter <hunterch@vmware.com>
> Update AWS SDK to latest version

- .gitignore
- .goreleaser.yml
- install.sh
This makes it so debug lines in stack traces no longer contain the path of the directory where the binary was built.
> trim build machine specific directory path from binaries

- internal/commands/bake.go
- internal/commands/bake_test.go
- main.go
this makes bake more like the other commands and hides the service configuration
> refactor: move bake setup func to bake.go command file

- internal/commands/validate.go
- main.go
Fixed a nil reference problem on the validate command introduced after
some refactoring.
Authored-by: Jhonathan Aristizabal <jhonathana@vmware.com>
> fixed nil reference error on validate command

- internal/history/release_test.go
Removed test that was running on a non-deterministic way locally and
being skipped on our CI.
Co-authored-by: Jhonathan Aristizabal <jhonathana@vmware.com>
Co-authored-by: Wayne Adams <wadams@pivotal.io>
> removed unused test

- internal/commands/bake.go
- internal/commands/release_notes.go
The constructor for the ReleaseNotes command expected to be called when the current directory is in a git repo. This is not always true and some existing scripts expect to run kiln from a temporary directory. To not break those scripts, the repository field on release notes is not set in the Execute method and not the constructor.
When testing the issue, I noticed the file name is a bit weird when there is no version set. So I also made the default output file name not have a dash when the version is not configured.
> fix: bake fails in tmp dir

- .goreleaser.yml
This will add automatic builds for Apple computers with M1 architecture to published releases.
It changes the names of build artifacts to include architecture, as well.
> Add darwin_arm64 builds to goreleaser

- internal/release/notes_data.go
- pkg/history/decode.go
- pkg/history/historic.go
- pkg/history/historic_test.go
the package interacts with history it is not itself a thing from the past
> refactor: rename package historic to history

- internal/acceptance/workflows/scenario/step_funcs_exec_test.go
- internal/acceptance/workflows/scenario/step_funcs_github_test.go
- internal/acceptance/workflows/scenario/step_funcs_tile_test.go
- internal/commands/bake_internal_test.go
- internal/commands/cache_compiled_releases_test.go
- internal/commands/release_notes_test.go
- internal/component/bump_internal_test.go
- internal/component/bump_test.go
- internal/component/github_release_source_internal_test.go
- internal/component/github_release_source_test.go
- internal/release/notes_data_test.go
- internal/release/notes_page_test.go
- internal/release/notes_template_test.go
- pkg/cargo/kilnfile_helpers_test.go
- pkg/cargo/kilnfile_test.go
- pkg/cargo/kilnfile_validate_test.go
- pkg/history/historic_test.go
- pkg/tile/metadata_test.go
- pkg/tile/releases_test.go
this makes it easier for non-mac developers to contribute
> refactor: use . import instead of Ω (non-ascii) character

- pkg/cargo/kilnfile_validate.go
- pkg/cargo/kilnfile_validate_test.go
This is to fix an issue that occurred when we removed a removed release source.
`kiln validate` will now fail when a release source for a release specified in the Kilnfile.lock is not found in the Kilnfile.
./Kilnfile.lock
```diff
releases:
- name: banana
version: 1.2.3
release_source: missing-release-source
```
./Kilnfile
```yaml
release_sources:
- type: s3
```
> feature(kiln validate): ensure a release source config exists for each release lock

- internal/commands/release_notes.go
- internal/commands/release_notes_test.go
- internal/commands/testdata/release_notes_output.md
- pkg/notes/fakes/trainstat_client.go
- pkg/notes/notes.go.md
- pkg/notes/notes_data.go
- pkg/notes/notes_data_test.go
- pkg/notes/notes_page_test.go
- pkg/notes/testdata/runtime-rn.html.md.erb
- Add -tu flag to release notes command to specify a different trainstat url
Authored-by: Pablo Rodas <prodas@vmware.com>
> feat: fetch release notes for component bumps from trainstat

- internal/commands/test_tile.go
- internal/commands/test_tile_test.go
**Minor changes to the log output when running `kiln test`**
Before:
After:
**Change docker image name to `kiln_test_dependencies:vmware` instead of `dont_push_me_vmware_confidential:123`**
Before:
After:
> Minor changes to kiln output and docker image name

- pkg/planitest/manifest.go
- pkg/planitest/product_service.go
- pkg/planitest/product_service_test.go
This does the same thing and has tests: https://pkg.go.dev/github.com/pivotal-cf/kiln@v0.80.0/pkg/tile#ReadMetadataFromFile
Initially, I wanted to add test coverage; however, I noticed that I could just use the well tested implementation from the tile package. It has the same semantics as the original implementation. Then I thought, maybe we should just deprecate this function and recommend using the one from tile.
I also added some linter warning "fixes" in this commit.
> remove proofing.ExtractTileMetadataFile

- internal/commands/manifest_test_docker/Dockerfile
- internal/commands/test_tile.go
- internal/commands/test_tile_acceptance_test.go
- internal/commands/test_tile_test.go
- internal/commands/testdata/tas_fake/tas/migrations/.gitignore
- internal/commands/testdata/tas_fake/tas/migrations/package.json
- main.go
- default `kiln test` runs migration and manifest tests now
- flags `--manifest-only` and `--migrations-only` added to test command
- Node.js/npm added to Dockerfile for test command
> feat: add migrations test workflow to test command

- main.go
If there is an error loading the local SSH provider (e.g. there is no running ssh-agent), it will be logged to standard error instead of swallowed. Panicking on this error breaks acceptance tests, so logging is the next best thing.
> fix: log errors when loading SSH provider

- internal/acceptance/workflows/acceptance_test.go
- internal/acceptance/workflows/scenario/initialize.go
- internal/acceptance/workflows/scenario/shared_state.go
- internal/acceptance/workflows/scenario/utilities.go
- internal/acceptance/workflows/using_kiln.feature
- pkg/cargo/kilnfile.go
The acceptance tests failure was caused by a change introduced in Masterminds/semver/v3. The comparison semantics for major 0 changed. The problem is summarized in this playground: https://go.dev/play/p/t5beNbYVR9K. I changed the zero value of the cargo.ComponentSpec version field from ">0" to ">=0" go get the same behavior as before.
The first commit in this branch fixes the issue. I found some other issues with the acceptance tests that caused failures on MacOS. I fixed those and refactored to make build failures easier to understand.
> fix acceptance tests after semver/v3 bump

- go.mod
- versions can only retract lower or equal versions. so we're going to push a v1.0.1 tag that retracts itself and v1.0.0
see https://github.com/golang/go/issues/60336
> dev ops: retract major versions

- .github/workflows/release.yml
We need to stabilize the flags, commands, **and package api** before we ship 1.0.
> only release v0 releases

- pkg/tile/metadata.go
- pkg/tile/metadata_test.go
tile-generator creates metadata filenames that are not "metadata/metadata.yml" with this change you can parse those tiles with the tile.ReadMetadata* functions
fixes: #403
> feat: parse non-standard metadata filenames

- internal/commands/find_stemcell_version.go
- internal/commands/find_stemcell_version_test.go
- pkg/cargo/kilnfile.go
- pkg/cargo/kilnfile_test.go
For a while we have maintained a switch statement that mapped stemcell slugs like "ubuntu-jammy/1.2" to product slugs like "stemcells-ubuntu-jammy". This was annoying but not that big of an issue because it we do it every year or so. Instead of continuing this pattern, lets add a field to the Kilnfile so the CLI does not need to change when a new stemcell is released.
This change helps me with my buildpack work because, I want to be able to compile releases against stemcells and I want the particular stemcell to be specified in the tile source. I don't want to maintain the same switch statement in both Kiln and in the buildpack. I intend to import these functions into the buildpack.
> feat: allow TanzuNet slug to be set in the Kilnfile stemcell criteria

- internal/component/s3_release_source.go
- pkg/cargo/files_test.go
- pkg/cargo/kilnfile.go
I created this PR based on #401 to do some refactors before merging the changes @abg made.
> add S3 aws role arn

- README.md
- TILE_AUTHOR_GUIDE.md
This is a response to a request to help tile authors switch to Kiln from tile-generator or other tools and for existing kiln users to better understand and use the tool.
It has my opinions that are informed by PPE's kiln usage.
Some of the content in this file is already in the README. This is duplicate documentation but I think this is a good thing. The README is more in-depth; this is more beginner friendly.
> add tile author guide for new Kiln users

- internal/component/github_release_source.go
- internal/component/github_release_source_internal_test.go
tags should have a v prefix. Let's do the happy thing first.
> fix: check v prefixed tag first

- go.mod
- go.sum
- internal/acceptance/workflows/using_kiln.feature
- internal/commands/flags/parse.go
- internal/commands/glaze.go
- internal/commands/glaze_test.go
- internal/commands/init_test.go
- main.go
- pkg/cargo/kilnfile.go
- pkg/cargo/kilnfile_test.go
- **`kiln glaze`**: pins all releases to exact version in current Kilnfile.lock
The release in the Kilnfile is skipped if it has the field value `always_float: true`
- **`kiln glaze --undo`**: "unpins" by pinning component version according to glaze_behaivor
The release in the Kilnfile gets it's version constraint set based on the value of `maintenance_version_bump_policy`. 
The permitted values are:
- "LockNone"
- "LockMajor" (this is also the default for when the value is the empty string or is not set)
- "LockMinor"
- "LockPatch"
The stemcell version constraint is not changed by this command.
The business logic is in the cargo package the command code does not exercise the functionality.
The Glaze command tests do not test functionality; they exercise the flag parsing and pass values …
> Add feature to specify which BOSH Release Tarball versions are locked and how BOSH Release Tarball versions are unlocked

- go.mod
- internal/component/artifactory_test.go
- internal/component/errors.go
- internal/component/github_release_source.go
When a github-release source is not found, kiln aborts early without trying additional release sources.
This change ensures the github release source reports "ErrNotFound" so that subsequent release sources can be tried.
Bumped go.mod -go=1.20 to pull in "errors.Join".  kiln is already built with Go 1.20 so this seems reasonable.
> component: consistently handle not found errors

- example-tile/bosh_variables/some-ca-certificate.yml
- example-tile/bosh_variables/some-secret.yml
> Kiln cannot parse bosh variables when given as top level array.

- go.mod
- go.sum
- pkg/tile/metadata.go
- pkg/tile/metadata_test.go
This will be helpful for making kiln test tile revisions against recently released tiles.
I intend to use this on a few upcoming features but am adding it now because this function is a helpful utility that TAS Operability may get value from.
I intentionally did not use the pivnet package because we use various versions of that module in this package. Once https://github.com/pivotal-cf/kiln/pull/318 is merged, we may want to re-evaluate this API. As it is, this implementation might work with Artifactory. I expect a future utility function to call this and pass in the appropriate information from a `pivnet.ProductFile` (ppet has an example of how to do this if the test comment is not enough).
This test change also switches from "gomega" to "testify/assert" for the tile package. We have …
> add function to tile package for reading metadata from a tanzunet product file

- go.mod
- go.sum
- internal/commands/fakes/pivnet_product_files_service.go
- internal/commands/fakes/pivnet_release_dependencies_service.go
- internal/commands/fakes/pivnet_release_upgrade_paths_service.go
- internal/commands/fakes/pivnet_releases_service.go
- internal/commands/fakes/pivnet_user_groups_service.go
- internal/commands/publish.go
- internal/commands/publish_test.go
- pkg/notes/internal/fakes/historic_kilnfile.go
- pkg/notes/internal/fakes/historic_version.go
- pkg/notes/internal/fakes/issue_getter.go
- pkg/notes/internal/fakes/issues_by_repo_lister.go
- pkg/notes/internal/fakes/issues_service.go
- pkg/notes/internal/fakes/milestone_lister.go
- pkg/notes/internal/fakes/releases_service.go
- pkg/notes/internal/fakes/revision_resolver.go
- pkg/notes/notes_data.go
dependabot is not bumping major versions so I am doing it manually
> bump (go-pivnet): import v7 everywhere

- internal/test/container.go
- internal/test/integration_test.go
I thought there was a problem with kiln when it was just my machine.
This test surfaces the daemon being out of date.
This is my error log.
```
=== RUN   TestDockerIntegration
=== RUN   TestDockerIntegration/the_test_succeeds
kiln test: 2023/09/05 11:20:55 connecting to ssh socket "/private/tmp/com.apple.launchd.jplCwFZ1Ie/Listeners"
kiln test: 2023/09/05 11:20:55 ensuring ssh agent keys are configured
kiln test: 2023/09/05 11:20:55 pinging docker daemon
kiln test: 2023/09/05 11:20:55 completed session setup
kiln test: 2023/09/05 11:20:55 creating test image
integration_test.go:41: 
Error Trace:    /Users/hunterch/workspace/tile-srp/kiln/internal/test/integration_test.go:41
Error:          Received unexpected error:
failed to load cache key: failed to fetch remote …
```
> refactor(test): fail integration tests when docker daemon is out of date

- pkg/cargo/bosh_release.go
- pkg/cargo/bosh_release_test.go
A confusing error happens sometimes when fetch fails. This change makes the error mesage clearer.
Instead of the error
> could not execute "bake": failed to parse releases: EOF
the user should see
> could not execute "bake": failed to parse releases: BOSH release tarball some-release-1.2.3.tgz is an empty file
We should also make sure fetch is cleaning up after itself on failure.
> Kiln bake logs confusing error when the tarball is empty (this happens sometimes when fetch fails)

- internal/commands/release_notes.go
- pkg/notes/notes_data.go
- pkg/notes/notes_data_test.go
- Add window flag to release-notes command
Authored-by: Pablo Rodas <prodas@vmware.com>
> fix: Don't override pre ga release notes

- internal/commands/test_tile.go
- internal/commands/test_tile_test.go
Add a new flag --silent to hide the output
> feat: Make kiln test verbose by default

- internal/builder/tile_writer.go
fixes: #354
There may be other inappropriate uses of filepath library in other places but this fixes it for tile building.
> use zip compliant path separator

- internal/acceptance/workflows/baking_a_tile.feature
- internal/acceptance/workflows/scenario/step_funcs_exec.go
- internal/acceptance/workflows/scenario/step_funcs_tile_source_code.go
- internal/commands/bake.go
- internal/commands/bake_test.go
- internal/test/integration_test.go
- pkg/notes/notes_data.go
- pkg/source/bake_record.go
- pkg/source/bake_record_test.go
The `bake --final` command should be used when baking a final tile.
Please see [feat(bake): add flag to block writing bake_record](https://github.com/pivotal-cf/kiln/pull/475/commits/14bc47c2a0642843fefa6cbed91a43ea8ff65049) to review the functionality change.
---
This PR includes two additional unrelated commits:
- the result of running gofumpt
- refactoring a test that fails when docker is not reachable even though the tests using docker are skipped
> add final flag to bake

- internal/builder/interpolator.go
- internal/builder/interpolator_test.go
- internal/builder/kiln_metadata.go
I found that we did not have the kiln version and commit shas in quite a few tile metadatas. This should fix that.
> improve interpolate is not adding kiln_metadata

- internal/component/artifactory.go
- internal/component/artifactory_test.go
This is based on https://github.com/pivotal-cf/kiln/pull/472. That PR won't get tested because it is from a fork. This PR also rebases on main.
---
We were blocked from using `kiln` with other Artifactory servers, in our case development servers, due to `find-release-version` and `update-release-version` behaving differently from `fetch` for `artifactory` release sources.
The issue was found in `internal/component/artifactory.go` `DownloadRelease` where `/artifactory` is always appended to the server url:
```go
downloadURL := ars.ArtifactoryHost + "/artifactory/" + ars.Repo + "/" + remoteRelease.RemotePath
```
**failing**
```
➜  hello-tile git:(feat/artifactory-source) ✗ :workspace/hello-tile$ kiln find-release-version --release hello-release --no-download -vr artifactory_username="admin" …
```
> normalize Artifactory URL

- internal/commands/bake.go
- internal/commands/bake_test.go
Our team recently experienced CI failures when trying to bake a tile, after passing in the [tas variables file](https://github.com/pivotal/tas/blob/main/tas/variables/srt.yml)
That file has the properties:
`tile_name: SRT`
The result was a strange error: 'tile_name value must be a string got value "SRT" with type string'
After investigating more, we found [this commit](https://github.com/pivotal-cf/kiln/commit/ce05d124b98f985d14c700afebfb8a9d0eb13e8d#diff-cf90d1c4858c9124c40badad400dbe3aafed9ad0c7a3c72b36e14532b6d6bf25R588) included a small typo in how the 'ok' value is handled
Worth noting - it was very hard to test this via the existing Bake tests. Because of this, we needed to export the function to be able to test it properly, but we know this is probably not ideal.
Our hope is you …
> Fixes bug when reading tile_name variable

- internal/component/artifactory.go
- internal/component/artifactory_test.go
Resolves https://github.com/pivotal-cf/kiln/issues/474
verified local tests covers change.
Tested following subcommands against an artifactory that required authentication:
- find-release-version
- update-stemcell
- update-release
> use basic auth for all request to artifactory if credentials are defined

- pkg/notes/testdata/runtime-rn.html.md.erb
This PR updates CAPI v2 docs links from `apidocs.cloudfoundry.org` to `v2-apidocs.cloudfoundry.org`.
The goal is to signal that v3 is the primary API, also a necessary step in eventually sunsetting v2.
The infrastructure hosting the app serving docs at apidocs.cloudfoundry.org is expected to go down imminently, so this change is needed to avoid dead links.
See capi-release PRs [#440](https://github.com/cloudfoundry/capi-release/pull/440) and [#441](https://github.com/cloudfoundry/capi-release/pull/441)
> Update CAPI v2 docs links to new subdomain

- internal/commands/update_release.go
- internal/commands/update_stemcell.go
- internal/commands/validate.go
- internal/commands/validate_test.go
- pkg/cargo/validate.go
- pkg/cargo/validate_test.go
- pkg/planitest/internal/config.go
- pkg/planitest/internal/om_runner.go
Golden Path requires tile authors to only use artifactory. This new flag allows us to upstream the requirement to Kiln. 
This doesn't introduce any breaking changes; new behavior is effectively feature flagged.
Story Id: TPCF-10575
> Kiln validate resource type allow list

- internal/test/Dockerfile
Avoids the issue:
> $ kiln test
> could not execute "test": failed to read downloaded context: failed to load cache key: Get "http://build-context-kynariop8p16gn9g8regr8efz": context not found
> Update dockerfile syntax to recommended value

- pkg/cargo/bosh_release.go
Reads in boshreleases a chunk at a time + does a streaming sha1sum while discarding the memory, rather than reading the entirety of the boshrelease into memory and then discarding.
> Reduce memory usage when calculating release shasum

- internal/commands/update_stemcell.go
- internal/commands/update_stemcell_test.go
In our automated system we always use the latest version of a stemcell and dependent compiled releases and have automation that attempts to keep the Kilnfile.lock current using `update-stemcell` and `find-release-version` / `update-release`.
On occasion:
when a new release and stemcell are created close together
and while trying to update the stemcell
the current release version in the Kilnfile.lock may not have a matching compiled release for the new stemcell.
Scenario example:
- compiled release exists for: release-v1-stemcell-v1
- release bumped: release-v2-stemcell-v1
- new stemcell available but build fails for: release-v2-stemcell-v2
- release bumped, build succeeds: release-v3-stemcell-v2
This leaves the following compiled releases available:
- release-v1-stemcell-v1
- …
> Add option to update releases while updating stemcell

- internal/commands/update_stemcell.go
- internal/commands/update_stemcell_test.go
- internal/component/artifactory_release_source.go
- internal/component/artifactory_release_source_test.go
- internal/component/bosh_io_release_source.go
- internal/component/bosh_io_release_source_test.go
implements #492 
* Only download releases if determining the SHA1 remotely was not possible.
* Updates artifactory `GetMatchedRelease` to include remote SHA1 of matched release from remote
* Updates bosh.io `GetMatchedRelease` to include remote SHA1 of matched release from remote
* Other release sources do not appear to support determining the remote SHA1.
> for update-stemcell, only download releases if necessary 

- pkg/planitest/internal/ops_manifest_runner_test.go
- pkg/planitest/product_service.go
file.
ops-manifest has an [option](https://github.com/pivotal-cf/ops-manager/blob/releases/3.0/gems/ops-manifest/exe/ops-manifest) to override the dollar overrides file. This file is used when tile configuration references $ properties (e.g $runtime)
This commit just adds the possibility to configure kiln test to pass that value to ops-manager in the same way it passes tile-config and tile-manifest overrides.
> kiln test: Allow for configuration of ops-manifest dollar overrides

- internal/test/Dockerfile
kiln test does not work with buildkit version 1.11+. It errors with cache key not found.
> fix: fix syntax directive version

- internal/component/artifactory_release_source.go
- internal/component/bosh_io_release_source.go
- internal/component/github_release_source.go
- internal/component/release_source.go
- internal/component/s3_release_source.go
- **Add the remote version to the download log message**
- **Remove the file info log line from the Artifactory release source**
> Improve debug output

- internal/acceptance/workflows/scenario/initialize.go
- internal/acceptance/workflows/scenario/step_funcs_kiln.go
- internal/acceptance/workflows/updating_releases.feature
- internal/acceptance/workflows/updating_stemcell.feature
- internal/commands/update_release.go
- internal/commands/update_stemcell.go
- internal/commands/update_stemcell_test.go
- internal/component/artifactory_release_source.go
- internal/component/artifactory_release_source_test.go
- internal/component/bosh_io_release_source.go
- internal/component/bosh_io_release_source_test.go
- internal/component/github_release_source.go
- pkg/cargo/bosh_release.go
This PR re-applies the changes from #493 with the addition of a without-download
flag to control the behaviour.
> Add a without-download flag to update-stemcell to skip release downloads

- .github/workflows/create-debugging-artifact.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- TILE_AUTHOR_GUIDE.md
- internal/acceptance/workflows/baking_a_tile.feature
- internal/acceptance/workflows/generating_release_notes.feature
- internal/acceptance/workflows/glaze.feature
- internal/acceptance/workflows/scenario/step_funcs_github_test.go
- internal/acceptance/workflows/scenario/step_funcs_tile_test.go
- internal/acceptance/workflows/testdata/tiles/v1/Kilnfile
- internal/acceptance/workflows/testdata/tiles/v1/Kilnfile.lock
- internal/acceptance/workflows/testdata/tiles/v1/README.md
- internal/acceptance/workflows/testdata/tiles/v1/notes/release_notes.md.erb
- internal/acceptance/workflows/testdata/tiles/v2/Kilnfile
- internal/acceptance/workflows/testdata/tiles/v2/Kilnfile.lock
- internal/acceptance/workflows/testdata/tiles/v2/README.md
- internal/acceptance/workflows/testdata/tiles/v2/go.mod
- internal/acceptance/workflows/updating_releases.feature
- internal/acceptance/workflows/updating_stemcell.feature
- internal/commands/release_notes_test.go
- internal/gh/uri_test.go
- pkg/cargo/validate_test.go
- Updated Chris test hello tile and hello release repo references to point to releen
- Updated upload-artifact github action to v4
- Pinned golangci-lint-action to v6.3.0 because of an error in the latest version
JIRA Link: https://vmw-jira.broadcom.net/browse/TNZ-32601
[TNZ-32601] - [Kiln]: Stop using Chris's hello release and tile repos for testing
Date: 27-Feb-2025
Authored-by: Ramkumar Vengadakrishnan <ramkumar.vengadakrishnan@broadcom.com>
> feat: [TNZ-32601] Updated hello tile and bosh repo references

- .github/workflows/release.yml
- .goreleaser.yml
[TNZ-36076] - [GCP Migration]: Migrate TAS Releng GCP projects to internal BSG GCP JIRA Link - https://vmw-jira.broadcom.net/browse/TNZ-36076 Updated on: 07-Apr-2025
Authored-by: Ramkumar Vengadakrishnan <ramkumar.vengadakrishnan@broadcom.com>
> feat: Removed code to push kiln image to GCR

- .github/workflows/create-debugging-artifact.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- internal/test/Dockerfile
- internal/test/container.go
- internal/test/integration_test.go
Skip the integration test for the internal/test package as it requires
access to Artifactory.
> Consume ops-manifest as a pre-built gem

- HomebrewFormula/kiln.rb
We need to fix the goreleaser. In the meantime I'm following in the footstep of the [previous release](https://github.com/pivotal-cf/kiln/commit/94385eeb789e744103e52c471ca5339a6d2b6829) and manually updating the formula.
> Brew formula update for kiln version v0.106.0
