pivotal-cf/kiln

- README.md
We are starting to gain traction on kiln. This change proposes preliminary updates to the readme so it's easier to understand what kiln is trying to accomplish. Feel free to make further changes before merging.
> Update README for ease of understanding

- commands/fetch.go
`--releases-directory` default is "releases"
`--assets-file default` default is "assets.yml"
> add reasable default and ability to make releases dir

- commands/publish.go
Authored-by: Christopher Hunter <chunter@pivotal.io>
[#169495176] kiln publish fails with Network Timeout error
> add retry loop and increase timeout for ListUserGroups HTTP Request

- acceptance/compile_built_releases_test.go
- acceptance/integration/publish_test.go
- commands/publish.go
- commands/update_release_test.go
- fetcher/bosh_io_release_source_test.go
- fetcher/s3_release_source.go
- fetcher/s3_release_source_test.go
- main.go
I reproduced and fixed the following test failures locally.
This time I will let them go through the branch CI before merging into main.
https://releng.ci.cf-app.com/teams/main/pipelines/tooling/jobs/test-kiln-pr/builds/166#L5fdd56c8:352
https://releng.ci.cf-app.com/teams/main/pipelines/tooling/jobs/integration-test-kiln/builds/224#L5fdd56df:292
> Fix race in tests and cert issue

- README.md
Added CI status badge to README
> added CI status badge to README

- internal/commands/cache_compiled_releases.go
Authored-by: Carlos Iriarte <ciriarte@users.noreply.github.com>
Authored-by: Marcela Lara <mlara@vmware.com>
> fix: isolate release source

- internal/commands/cache_compiled_releases.go
- internal/commands/cache_compiled_releases_test.go
Authored-by: Carlos Iriarte <ciriarte@users.noreply.github.com>
> fix: filter target ID correctly

- .goreleaser.yml
- internal/commands/cache_compiled_releases.go
- internal/commands/cache_compiled_releases_test.go
- internal/component/release_source.go
- internal/component/release_source_list.go
- internal/component/s3_release_source.go
- internal/component/s3_release_source_test.go
- fix: add preerelease support
- debug: add tracing to matching logic
> bugfix/cache compiled releases/isolate release source

- internal/release/notes_data.go
- internal/release/notes_data_test.go
this fixs the bug [#182763807]
Authored-by: Gary Liu <garyliu@vmware.com>
> fix: default regex for IssueTitle

- internal/commands/find_stemcell_version.go
Co-authored-by: Jhonathan Aristizabal <jhonathana@vmware.com>
Co-authored-by: Mark Stokan <stokanm@vmware.com>
> feat: added support for jammy stemcell on find-stemcell-version

- internal/acceptance/workflows/acceptance_test.go
- internal/acceptance/workflows/glaze.feature
- internal/acceptance/workflows/scenario/initialize.go
- internal/acceptance/workflows/scenario/step_funcs_tile_source_code.go
- internal/acceptance/workflows/using_kiln.feature
- internal/commands/glaze.go
- internal/commands/glaze_test.go
- main.go
sets the version constraint to the component/stemcell lock versions
Co-authored-by: David Timm <dtimm@vmware.com>
> feat (glaze): quickly pin releases in a Kilnfile

- internal/component/artifactory_release_source.go
- internal/component/bosh_io_release_source.go
- internal/component/github_release_source.go
Co-authored-by: Gary Liu <garyliu@vmware.com>
> log to stderr to not pollute the output

- internal/commands/fetch.go
- internal/commands/fetch_test.go
Co-authored-by: Gary Liu <garyliu@vmware.com>
> update usage message for fetch cmd

- internal/commands/generate_osm_manifest.go
- internal/commands/generate_osm_manifest_test.go
- internal/commands/glaze.go
- main.go
- pkg/cargo/kilnfile_helpers.go
[Exceptional OSM for Foundation OSS in TAS 4.0
](https://3.basecamp.com/4957863/projects/31968079)
> [Feat]: Generate OSM Manifest

- internal/commands/test_tile.go
- internal/commands/test_tile_test.go
Authored-by: Nick Rohn <nrohn@vmware.com>
> fix: kiln test docker output

- .github/workflows/release.yml
- .goreleaser.yml
- Update docker/login-action to v2
Authored-by: Ramkumar Vengadakrishnan <ramkumarv@vmware.com>
[#184667616] - Move Dockerhub images to GCR
> feat: Push images to gcr

- internal/builder/metadata_git_sha.go
This is a quick hack fix to the `git-metadata-sha` issue where it is falsely reporting a dirty work tree.
If you already fixed this on your branch, ignore this (and close the PR).
The unit tests are passing after the change. I am not sure if this is due to a lack of test coverage or because it is a safe internal refactor.
> fix git-metadata-sha calculation

- .github/workflows/codeql-analysis.yml
- .github/workflows/create-debugging-artifact.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Bump checkout to v3
Bump setup-go to v4
> bump Github Action versions

- README.md
Hoping to add some more examples of kilnfiles and kilnfile.lock files
> Update readme for kilnfile and kilnfile.lock

- .gitignore
the migration test adds this directory
> ignore node_modules directory

- go.mod
- go.sum
- internal/acceptance/bake/bake_test.go
- internal/commands/bake.go
- internal/commands/bake_test.go
skip all or nothing instead of passing specific directories
Authored-by: Nick Rohn <nrohn@vmware.com>
> feat: change --skip-fetch-directories to boolean

- internal/commands/fetch.go
Created this PR with changes from https://github.com/pivotal-cf/kiln/pull/444 to allow the pipeline to pass the tests. 
This is the same changes as PR 444
> add additional logs when removing releases

- .gitignore
- internal/acceptance/bake/bake_test.go
- internal/acceptance/workflows/baking_a_tile.feature
- internal/builder/interpolator.go
- internal/builder/kiln_metadata.go
- internal/builder/kiln_metadata_test.go
- internal/builder/metadata_git_sha.go
- internal/commands/bake.go
- internal/commands/bake_test.go
- pkg/source/bake_record.go
- pkg/source/bake_record_test.go
- test.sh
https://www.pivotaltracker.com/story/show/186802072
> bake records commit sha, kiln version, and product version

- README.md
With the new bake_configurations, it makes sense we add some documentation for the specification.
> document Kilnfile and Kilnfile.lock

- internal/builder/interpolator.go
- internal/builder/interpolator_test.go
Fixes #541
Signed-off-by: Max Brauer <mbrauer@vmware.com>
> Template into complex strings without quoting

- internal/component/artifactory_release_source.go
- internal/component/artifactory_release_source_test.go
- internal/component/release_source_test.go
> Revert "Find Release Version - Fix Inexact Artifactory Remote Matching"
